sudo: false

language: node_js

node_js:
  - "4.0"
  - "iojs"
  - "0.12"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - npm install -g npm
  - npm install -g node-gyp
  - node-gyp clean
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install
  - jspm install

script:
  - npm run test-all-travis
  - npm run lint
