sudo: false

language: node_js

# This encrypts environment variable JSPM_GITHUB_AUTH_TOKEN
# containing an encrypted token to access henrjk/connect-js on github
env:
  global:
    - secure:  "ilQYv0W6AU4udIE3ZrWBRuRllVgkJUHxHO6hzFoOYxl7MqEtStRa48eBLpG73MQE3QsXn5MPSsdGSgRaDW9vQCjrPWNPhZPXTOJiag9mHmdzZEuHNhDv2u04avbCW2Mtg5L+NitAiN+XIqgl/7G271OCG+hfqfDd7XOWoxi5xyeFOwzvRTd53nB1GL2in0vnkKIUfMNarMS+WtAZGES4pou8lJ6gQ5itJOAOAtB1renvDFx0hdl0TeDH7k4jYKZSGCmF507A+Zi9268tfWXtjT91e+DSE7W6HRvToA+WGkeDZXmM5Z6chod66OTcnROxTVWqqgM0UQ7XEZtRsqo2Wu1ARxj52hacgGKkI4MI1rYTbNO2R0bTw78y82g8spBq7Yo6TMEtDbrKLnEunUUz0bgn50/G/pK3pV0CMwqLqGazNDDl7EcZQLeN4TKL7dRcOTAVohcU+HJYFcd857ordxPqeiTZQI+1gcRqY2/ySBmJgaew+CAJAocG7MIKqxIiYnGWSe3NFxAFBgYiUBLSVAEifI57lfMN59Vosw9NY/APCnzT7b5R9W9jVFuj9OQMh6/h0QWqynql+xgYM35WfzjsPavWRunRIOmm0m9OOZnjUPwY8Vx/AJFaclQukBzcID7wR5E5YSSPhKBgglBMEO63bSdAy+T4jNjq36dpWxk="

node_js:
#  - "4.0"
#  - "iojs"
  - "0.12"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - npm install -g npm
  - npm install -g node-gyp
  - node-gyp clean
  - npm install -g jspm
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install
  - jspm install

script:
  - npm run test-all-travis
  - npm run lint
